### ISSUE TITLE
reload command and scripts

### ISSUE THREAD

**Issue by miztizm** [af/dotfiles#1]
Helllo
when i run a /reload command 
i have a 
   Error: failed to reload options from autosort.conf
   python: unable to run function "colorize_config_reload_cb"
   Error: failed to reload options from colorize_scripts.conf

where i need to look to fix it ? cause every seems looks normal for me
thanks

**Comment by af** [comment]
Hi,

Sorry, I'd like to help, but it looks like you're using a plugin or two that I'm not familiar with. If you join `#weechat` on freenode there are lots of friendly people there that might be able to figure it out.
